server:
  port: 8081
  address: localhost
  contextPath: /uaa
#spring数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myproject?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #指定数据连接沲
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis配置
mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:com/talelife/auth/mapper/*.xml
  type-aliases-package: com.talelife.auth.model
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params-count: countSql
#日志配置
logging:
  level.org.springframework.web: debug
  level.org.springframework.transaction: debug
  level.org.mybatis: debug
  level.com.talelife.auth: debug
  debug: false
security:
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**